FROM node:alpine

WORKDIR /app

#COPY ./package.json ./
COPY . .
#RUN npm install
RUN npm install @material-ui/core
RUN npm install @material-ui/icons
RUN npm install recharts


CMD ["npm", "run", "start"]

