FROM node:alpine as builder

WORKDIR /app

COPY ./package.json ./
RUN npm install
RUN npm install @material-ui/core
RUN npm install @material-ui/icons
RUN npm install recharts
RUN npm install node-sass@latest

COPY . .

CMD ["npm", "run", "start"]

