apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: jkolden/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:

deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
