apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ociportal-com-tls
spec:
  secretName: ociportal-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ociportal.com
  dnsNames:
    - ociportal.com
    - www.ociportal.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ociportal.com
          - www.ociportal.com
